services:
  db:
    image: postgres:${POSTGRES_VERSION}
    restart: always
    container_name: bazar_sp_db
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    ports:
      - ${POSTGRES_LOCAL_PORT}:${POSTGRES_CONTAINER_PORT}
